var locationData = [
    {
        "name"       : "Lone Tree Station",
        "url"        : "lone_tree_station",
        "set"        : "valleyBase",
        "setCardNum" : 2,
        "isPivotal"  : true,
        "x"          : 2227,
        "y"          : 2194,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Forest",
        "trait3"     : "Ranger Station",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "White Sky",
        "url"        : "white_sky/",
        "set"        : "valleyBase",
        "setCardNum" : 1,
        "isPivotal"  : true,
        "x"          : 3025,
        "y"          : 2443,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Water",
        "trait3"     : "Trail",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Northern Outpost",
        "url"        : "northern_outpost/",
        "set"        : "valleyBase",
        "setCardNum" : 3,
        "isPivotal"  : true,
        "x"          : 3320,
        "y"          : 1647,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Spire",
        "url"        : "spire",
        "set"        : "valleyBase",
        "setCardNum" : 9,
        "isPivotal"  : true,
        "x"          : 2830,
        "y"          : 3244,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Branch",
        "url"        : "branch",
        "set"        : "valleyBase",
        "setCardNum" : 15,
        "isPivotal"  : true,
        "x"          : 3622,
        "y"          : 3456,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Forest",
        "trait3"     : "Trail",
        "trait4"     : "Ascent",
        "trait5"     : null
    },
    {
        "name"       : "The Fractured Wall",
        "url"        : "fractured_wall",
        "set"        : "valleyBase",
        "setCardNum" : 12,
        "isPivotal"  : true,
        "x"          : 4083,
        "y"          : 2714,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Ruin",
        "trait3"     : "Water",
        "trait4"     : "Ascent",
        "trait5"     : null
    },
    {
        "name"       : "Meadow",
        "url"        : "meadow/",
        "set"        : "valleyBase",
        "setCardNum" : 21,
        "isPivotal"  : true,
        "x"          : 2559,
        "y"          : 4355,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Field",
        "trait3"     : "Trail",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Marsh of Rebirth",
        "url"        : "marsh_of_rebirth/",
        "set"        : "valleyBase",
        "setCardNum" : 32,
        "isPivotal"  : true,
        "x"          : 3585,
        "y"          : 5028,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Water",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Tumbledown",
        "url"        : "tumbledown",
        "set"        : "valleyBase",
        "setCardNum" : 37,
        "isPivotal"  : true,
        "x"          : 2841,
        "y"          : 5898,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Mountain",
        "trait3"     : "Water",
        "trait4"     : "Trail",
        "trait5"     : null
    },
    {
        "name"       : "Atrox Mountain",
        "url"        : "atrox_mountain",
        "set"        : "valleyBase",
        "setCardNum" : 4,
        "isPivotal"  : false,
        "x"          : 2752,
        "y"          : 1774,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Ascent",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Golden Shore",
        "url"        : "golden_shore/",
        "set"        : "valleyBase",
        "setCardNum" : 5,
        "isPivotal"  : false,
        "x"          : 3188,
        "y"          : 1967,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Mount Nim",
        "url"        : "mount_nim",
        "set"        : "valleyBase",
        "setCardNum" : 6,
        "isPivotal"  : false,
        "x"          : 3767,
        "y"          : 2285,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Ascent",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Boulder Field",
        "url"        : "boulder_field",
        "set"        : "valleyBase",
        "setCardNum" : 7,
        "isPivotal"  : false,
        "x"          : 2440,
        "y"          : 2622,
        "presence"   : 1,
        "trait1"     : "Field",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Ancestor's Grove",
        "url"        : "ancestors_grove",
        "set"        : "valleyBase",
        "setCardNum" : 8,
        "isPivotal"  : false,
        "x"          : 1814,
        "y"          : 2789,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Kobo's Market",
        "url"        : "kobos_market/",
        "set"        : "valleyBase",
        "setCardNum" : 10,
        "isPivotal"  : false,
        "x"          : 2144,
        "y"          : 3117,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Philosopher's Garden",
        "url"        : "the_philosophers_garden/",
        "set"        : "valleyBase",
        "setCardNum" : 13,
        "isPivotal"  : false,
        "x"          : 3427,
        "y"          : 3058,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The High Basin",
        "url"        : "the_high_basin",
        "set"        : "valleyBase",
        "setCardNum" : 14,
        "isPivotal"  : false,
        "x"          : 3952,
        "y"          : 3227,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Water",
        "trait3"     : "Trail",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Plummet",
        "url"        : "the_plummet/",
        "set"        : "valleyBase",
        "setCardNum" : 18,
        "isPivotal"  : false,
        "x"          : 1568,
        "y"          : 3545,
        "presence"   : 3,
        "trait1"     : "Mountain",
        "trait2"     : "Ascent",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Crossroads Station",
        "url"        : "crossroads_station",
        "set"        : "valleyBase",
        "setCardNum" : 23,
        "isPivotal"  : false,
        "x"          : 3194,
        "y"          : 3489,
        "presence"   : 1,
        "trait1"     : "Trail",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Furrow",
        "url"        : "the_furrow",
        "set"        : "valleyBase",
        "setCardNum" : 16,
        "isPivotal"  : false,
        "x"          : 4322,
        "y"          : 3492,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Biological Outpost",
        "url"        : "biological_outpost",
        "set"        : "valleyBase",
        "setCardNum" : 17,
        "isPivotal"  : false,
        "x"          : 3704,
        "y"          : 3855,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Headwaters Station",
        "url"        : "headwaters_station/",
        "set"        : "valleyBase",
        "setCardNum" : 20,
        "isPivotal"  : false,
        "x"          : 2127,
        "y"          : 3472,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Greenbriar Knoll",
        "url"        : "greenbriar_knoll/",
        "set"        : "valleyBase",
        "setCardNum" : 19,
        "isPivotal"  : false,
        "x"          : 2595,
        "y"          : 3798,
        "presence"   : 1,
        "trait1"     : "Field",
        "trait2"     : "Ruin",
        "trait3"     : "Trail",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Concordant Ziggurats",
        "url"        : "the_concordant_ziggurats",
        "set"        : "valleyBase",
        "setCardNum" : 22,
        "isPivotal"  : false,
        "x"          : 1875,
        "y"          : 4359,
        "presence"   : 1,
        "trait1"     : "Ruin",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Stoneweaver Bridge",
        "url"        : "stoneweaver_bridge",
        "set"        : "valleyBase",
        "setCardNum" : 11,
        "isPivotal"  : false,
        "x"          : 3168,
        "y"          : 4372,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Mound of the Navigator",
        "url"        : "mound_of_the_navigator",
        "set"        : "valleyBase",
        "setCardNum" : 26,
        "isPivotal"  : false,
        "x"          : 3614,
        "y"          : 4301,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Terravore",
        "url"        : "terravore/",
        "set"        : "valleyBase",
        "setCardNum" : 27,
        "isPivotal"  : false,
        "x"          : 4133,
        "y"          : 3991,
        "presence"   : 3,
        "trait1"     : "Biomeld",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Greenbridge",
        "url"        : "the_greenbridge",
        "set"        : "valleyBase",
        "setCardNum" : 28,
        "isPivotal"  : false,
        "x"          : 3839,
        "y"          : 4655,
        "presence"   : 2,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Michael's Bog",
        "url"        : "michaels_bog",
        "set"        : "valleyBase",
        "setCardNum" : 29,
        "isPivotal"  : false,
        "x"          : 3578,
        "y"          : 4681,
        "presence"   : 3,
        "trait1"     : "Water",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Cypress Citadel",
        "url"        : "the_cypress_citadel",
        "set"        : "valleyBase",
        "setCardNum" : 30,
        "isPivotal"  : false,
        "x"          : 3893,
        "y"          : 4896,
        "presence"   : 3,
        "trait1"     : "Forest",
        "trait2"     : "Water",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Frowning Gate",
        "url"        : "the_frowning_gate",
        "set"        : "valleyBase",
        "setCardNum" : 31,
        "isPivotal"  : false,
        "x"          : 3340,
        "y"          : 5120,
        "presence"   : 3,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Sunken Outpost",
        "url"        : "sunken_outpost",
        "set"        : "valleyBase",
        "setCardNum" : 33,
        "isPivotal"  : false,
        "x"          : 3790,
        "y"          : 5261,
        "presence"   : 2,
        "trait1"     : "Water",
        "trait2"     : "Ruin",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Archaeological Outpost",
        "url"        : "archaeological_outpost/",
        "set"        : "valleyBase",
        "setCardNum" : 25,
        "isPivotal"  : false,
        "x"          : 1960,
        "y"          : 5006,
        "presence"   : 1,
        "trait1"     : "Trail",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Rings of the Moon",
        "url"        : "rings_of_the_moon",
        "set"        : "valleyBase",
        "setCardNum" : 24,
        "isPivotal"  : false,
        "x"          : 2331,
        "y"          : 4892,
        "presence"   : 1,
        "trait1"     : "Ruin",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Alluvial Ruins",
        "url"        : "the_alluvial_ruins",
        "set"        : "valleyBase",
        "setCardNum" : 34,
        "isPivotal"  : false,
        "x"          : 2703,
        "y"          : 5269,
        "presence"   : 2,
        "trait1"     : "Ruin",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Bowl of the Sun",
        "url"        : "bowl_of_the_sun",
        "set"        : "valleyBase",
        "setCardNum" : 35,
        "isPivotal"  : false,
        "x"          : 3132,
        "y"          : 5395,
        "presence"   : 1,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Watcher's Rock",
        "url"        : "watchers_rock",
        "set"        : "valleyBase",
        "setCardNum" : 36,
        "isPivotal"  : false,
        "x"          : 2226,
        "y"          : 5862,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Chimney",
        "url"        : "the_chimney",
        "set"        : "legacyArcology",
        "setCardNum" : 1,
        "isPivotal"  : true,
        "x"          : 2950,
        "y"          : 1851,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Trail",
        "trait3"     : "Ruin",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Severed Artery",
        "url"        : "severed_artery",
        "set"        : "legacyArcology",
        "setCardNum" : 2,
        "isPivotal"  : true,
        "x"          : 2366,
        "y"          : 3770,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Trail",
        "trait3"     : "Ruin",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Branching Artery",
        "url"        : "branching_artery/",
        "set"        : "legacyArcology",
        "setCardNum" : 3,
        "isPivotal"  : true,
        "x"          : 2930,
        "y"          : 3643,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Trail",
        "trait3"     : "Ruin",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Terminal Artery",
        "url"        : "terminal_artery",
        "set"        : "legacyArcology",
        "setCardNum" : 4,
        "isPivotal"  : true,
        "x"          : 3506,
        "y"          : 3684,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Trail",
        "trait3"     : "Ruin",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Mycelial Conclave",
        "url"        : "mycelial_conclave",
        "set"        : "legacyArcology",
        "setCardNum" : 5,
        "isPivotal"  : true,
        "x"          : 3291,
        "y"          : 4300,
        "presence"   : 3,
        "trait1"     : "Pivotal",
        "trait2"     : "Forest",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Verdant Sphere",
        "url"        : "the_verdant_sphere/",
        "set"        : "legacyArcology",
        "setCardNum" : 7,
        "isPivotal"  : true,
        "x"          : 2721,
        "y"          : 5321,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Ruin",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Arboretum of Memory",
        "url"        : "arboretum_of_memory/",
        "set"        : "legacyArcology",
        "setCardNum" : 6,
        "isPivotal"  : true,
        "x"          : 3558,
        "y"          : 5424,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Forest",
        "trait3"     : "Ruin",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Cage",
        "url"        : "the_cage/",
        "set"        : "legacyArcology",
        "setCardNum" : 20,
        "isPivotal"  : true,
        "x"          : 2904,
        "y"          : 6334,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Ruin",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Oasis of Sunlight",
        "url"        : "oasis_of_sunlight/",
        "set"        : "legacyArcology",
        "setCardNum" : 10,
        "isPivotal"  : false,
        "x"          : 3473,
        "y"          : 1958,
        "presence"   : 1,
        "trait1"     : "Trail",
        "trait2"     : "Ruin",
        "trait3"     : "Cave",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Drenching Chamber",
        "url"        : "drenching_chamber/",
        "set"        : "legacyArcology",
        "setCardNum" : 9,
        "isPivotal"  : false,
        "x"          : 2251,
        "y"          : 2751,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Ruin",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Desert of Endless Night",
        "url"        : "desert_of_endless_night",
        "set"        : "legacyArcology",
        "setCardNum" : 11,
        "isPivotal"  : false,
        "x"          : 2634,
        "y"          : 3080,
        "presence"   : 1,
        "trait1"     : "Trail",
        "trait2"     : "Desert",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Orlin's Vault",
        "url"        : "orlins_vault",
        "set"        : "legacyArcology",
        "setCardNum" : 13,
        "isPivotal"  : false,
        "x"          : 3122,
        "y"          : 2985,
        "presence"   : 1,
        "trait1"     : "Trail",
        "trait2"     : "Ruin",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Scuttler Network",
        "url"        : "scuttler_network",
        "set"        : "legacyArcology",
        "setCardNum" : 14,
        "isPivotal"  : false,
        "x"          : 3519,
        "y"          : 2677,
        "presence"   : 2,
        "trait1"     : "Cave",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Silent Dormitories",
        "url"        : "silent_dormitories",
        "set"        : "legacyArcology",
        "setCardNum" : 16,
        "isPivotal"  : false,
        "x"          : 2759,
        "y"          : 4190,
        "presence"   : 1,
        "trait1"     : "Trail",
        "trait2"     : "Ruin",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Cerulean Curtain",
        "url"        : "cerulean_curtain/",
        "set"        : "legacyArcology",
        "setCardNum" : 12,
        "isPivotal"  : false,
        "x"          : 2341,
        "y"          : 4515,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Cave",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Cistern",
        "url"        : "the_cistern",
        "set"        : "legacyArcology",
        "setCardNum" : 15,
        "isPivotal"  : false,
        "x"          : 2405,
        "y"          : 4977,
        "presence"   : 2,
        "trait1"     : "Water",
        "trait2"     : "Ruin",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Carbonforged Maze",
        "url"        : "carbonforged_maze",
        "set"        : "legacyArcology",
        "setCardNum" : 17,
        "isPivotal"  : false,
        "x"          : 3387,
        "y"          : 4918,
        "presence"   : 1,
        "trait1"     : "Ruin",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Inverted Forest",
        "url"        : "inverted_forest",
        "set"        : "legacyArcology",
        "setCardNum" : 18,
        "isPivotal"  : false,
        "x"          : 2307,
        "y"          : 5435,
        "presence"   : 3,
        "trait1"     : "Trail",
        "trait2"     : "Forest",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Rootway",
        "url"        : "the_rootway",
        "set"        : "legacyArcology",
        "setCardNum" : 19,
        "isPivotal"  : false,
        "x"          : 2402,
        "y"          : 5827,
        "presence"   : 3,
        "trait1"     : "Cave",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Talpid's Squeeze",
        "url"        : "talpids_squeeze",
        "set"        : "legacyArcology",
        "setCardNum" : 8,
        "isPivotal"  : false,
        "x"          : 3367,
        "y"          : 5786,
        "presence"   : 2,
        "trait1"     : "Ruin",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    }
];